### ISSUE TITLE
Пытаюсь установить на виндовс

### ISSUE THREAD

**Issue by aderod** [appwilio/yakassa#1]
пишет:
`Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependenci
es. Run update to update them.
Nothing to install or update
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

In ProviderRepository.php line 208:

  Class 'Appwilio\YaKassa\YaKassaServiceProvider' not found

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1`

**Comment by jhaoda** [comment]
Изучайте composer.
